INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE) VALUES (default, '3d printer', 'A beginner friendly 3d printer', 1840.25);
INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE) VALUES (default, '3d printer2', 'A beginner friendly 3d printer', 1790.25);
INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE) VALUES (default, '3d printer3', 'A beginner friendly 3d printer', 1450.25);
INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE) VALUES (default, '3d printer4', 'A beginner friendly 3d printer', 1210.25);
INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE) VALUES (default, '3d printer5', 'A beginner friendly 3d printer', 1140.25);
INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE) VALUES (default, '3d printer6', 'A beginner friendly 3d printer', 2840.25);
INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE) VALUES (default, '3d printer7', 'A beginner friendly 3d printer', 3240.25);
INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE) VALUES (default, '3d printer8', 'A beginner friendly 3d printer', 2840.25);
INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE) VALUES (default, '3d printer9', 'A beginner friendly 3d printer', 3640.25);
INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE) VALUES (default, 'PC 01', 'A portable computer', 1840.25);
INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE) VALUES (default, 'PC 02', 'A portable computer', 1740.25);
INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE) VALUES (default, 'PC 03', 'A portable computer', 1560.25);
INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE) VALUES (default, 'PC 04', 'A portable computer', 1780.25);
INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE) VALUES (default, 'PC 05', 'A portable computer', 1210.25);
INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE) VALUES (default, 'PC 06', 'A portable computer', 1980.25);
INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE) VALUES (default, 'PC 07', 'A portable computer', 2340.25);
INSERT INTO PRODUCT(ID, NAME, DESCRIPTION, PRICE) VALUES (default, 'PC 08', 'A portable computer', 2440.25);